### ISSUE TITLE
the mAP@1000 for mnist is only 30.39%

### ISSUE THREAD

**Issue by LiuChaoXD** [8uos/HashGAN-Pytorch#1]
I follow your steps.
first, train the model by " python HashGAN.py --train "
second, the trained model's ckpt is saved at "results/mnist/temp/models/G_final.ckpt and results/mnist/temp/models/D_final.ckpt". So the evaluation is processed by
 "python HashGAN.py --eval \
                  --G_dict=./results/mnist/temp/models/G_final.ckpt \
                  --D_dict=./results/mnist/temp/models/D_final.ckpt"

However, the result is lower a lot than the reported result 94.31 in the paper.

I don't know where I miss.

**Comment by khoadoan** [comment]
We had the same problem with reproducibility of this paper. Then, we contacted the author but he refuse to release the code. So far, we haven't seen any papers which could directly compare with HashGAN by rerunning it. What I'm finding interesting is that even some of the Supervised Deep Hashing methods could not have this good of the results on MNIST.

**Comment by 8uos** [comment]
Sorry for the late reply.
I also failed to reproduce the paper's performance, and I reported that in Discussion.md (in Korean).

**Comment by LiuChaoXD** [comment]
ok,
thanks for your reply.
